######################################################################
# Automatically generated by qmake (3.1) Mon Mar 13 14:02:54 2023
######################################################################

TEMPLATE = app
TARGET = ninja-fruit
QT = core gui widgets
HEADERS += mainwindow.h fruit.h
SOURCES += mainwindow.cpp main.cpp fruit.cpp

